### ISSUE TITLE
Remove Caneda

### ISSUE THREAD

**Issue by victorchoke** [kitspace/awesome-electronics#15]
I think it will be useful to add caneda 
https://github.com/Caneda/Caneda

**Comment by kasbah** [comment]
Sorry I missed this somehow. Feel free to send a pull-request to add this.

**Comment by stevestock** [comment]
Closed by https://github.com/kitspace/awesome-electronics/commit/a3e116ffe016714a8a3f3bd0131e93e1332e8f0f

**Comment by kasbah** [comment]
Though looking at the repo now, it doesn't seem very active. Does it actually work well?

**Comment by vinceh121** [comment]
Compiles on Debian Bullseye, has the basic stuff, could not get component libraries to work

**Comment by kasbah** [comment]
Thanks for checking. Would you recommend it to someone? I am leaning towards removing it again.

**Comment by vinceh121** [comment]
Apart from the broken libraries it seems usable for - at least - beginners and toying around with simulation but not for production as it doesn't seem to be able to export to gerbers

**Comment by kasbah** [comment]
I think we should remove it again.

**Comment by vinceh121** [comment]
Removed in 0d1617652f351a248de01344dcfa0b7ce5ee2f1e
