### ISSUE TITLE
Add stencil manufacturers

### ISSUE THREAD

**Issue by Timmmm** [kitspace/awesome-electronics#7]
e.g. https://www.oshstencils.com/ (no relation to OSHPark)

**Comment by kasbah** [comment]
Yeah, good Idea. If people know any others we can turn it into a section.

**Comment by joaoantoniocardoso** [comment]
I think I can manage to list some and create a pull. 
I will start by reading [this eevblog discussion](https://www.eevblog.com/forum/manufacture/good-and-low-cost-prototype-stencils/). Any suggestions?

**Comment by kasbah** [comment]
I think a _lot_ of the PCB batching services now offer stencils.

**Comment by joaoantoniocardoso** [comment]
Yeah, you are right, I notice that too:
PCB and/or stencils:
[PCBWay](https://www.pcbway.com)
[SeedStudio](https://www.seeedstudio.com)
[JCLPCB](https://jlcpcb.com)
[AllPCB](https://www.allpcb.com)
[Elecrow](https://www.elecrow.com)

Only stencils:
[Pololu](https://www.pololu.com)
[OshStencils](https://www.oshstencils.com)

**Comment by kasbah** [comment]
Add Aisler and copy it over ;)

**Comment by tapyu** [comment]
@kasbah should we close this issue?
