### ISSUE TITLE
Is there any service that can output the pcbdoc suffix file directly to the gerber file?

### ISSUE THREAD

**Issue by shawon1220** [kitspace/awesome-electronics#79]
@kasbah 
Is there any service that can output the pcbdoc suffix file directly to the gerber file?
The way I know so far is to first convert the file to kicad. [altium2kicad](https://github.com/thesourcerer8/altium2kicad)  But this has a lot of compatibility issues. 
So I don't know how some systems handle it, uploading pcbdoc files they can output gerber very accurately.

**Comment by kasbah** [comment]
Not that I know of.
