### ISSUE TITLE
Add ZofZPCB 3d Gerber Viewer

### ISSUE THREAD

**Issue by normaldotcom** [kitspace/awesome-electronics#8]
...an awesome 3d gerber viewer that will even model components on the board from an IPC file.

https://www.zofzpcb.com/

**Comment by kasbah** [comment]
Cool, giving this a go as it seems to run in WINE on Linux. It seems very powerful but the GUI is awful and it can be _very_ slow and processor intensive heavy at some points.

**Comment by normaldotcom** [comment]
Haha the GUI is a bit of a challenge to get used to, but the functionality is pretty great. I also primarily use it under WINE. If your CAM job has normal extensions, autodetection of the project via File -> Compose -> Auto is really convenient.

**Comment by kasbah** [comment]
"normal" extensions :laughing: We are trying to make sense of all the ways to name Gerbers in [whats-that-gerber](https://github.com/tracespace/whats-that-gerber). It's good it's got something built in though. 

I am up for adding this, could you prepare a PR?
