### ISSUE TITLE
Reintroducing EasyEDA?

### ISSUE THREAD

**Issue by hattesen** [kitspace/awesome-electronics#83]
Hi,

EasyEDA was removed from the list back in 2019. Would it not qualify to be added to the EDA list again? It has a [free version](https://easyeda.com/page/pricing) and exists as both online and client app variants.
Furthermore, it has all LCSC.com components (and the JLCPCB.com subset) available, including 3D models.

I'd be happy to submit a PR.

**Comment by kasbah** [comment]
Sure, thanks!
