### ISSUE TITLE
Collection of Electrical Engineering Subject resources

### ISSUE THREAD

**Issue by 200901002** [kitspace/awesome-electronics#87]
I made a website to share electrical engineering resources, to understand concepts, it has youtube videos book suggestion etc.

[Airgapflux](https://airgapflux.co.in)
[Airgapflux explore page](https://airgapflux.co.in/explore.php)

**Comment by kasbah** [comment]
Hey, thanks for the suggestion. I think it's a really good start to a site. For the time being it looks a little early to put it on our awesome list, it's hard to get a good idea from browsing the site what and how an EE beginner could learn from it, it seems a little disorganised to be honest. 

The way I think of this list is what are the resources most experienced EE's will already know about and I think there it misses the mark. Maybe in a few years?

**Comment by 200901002** [comment]
Dear Kaspar,

Thank you for taking the time to review my website and providing your
valuable feedback. I appreciate your constructive criticism and the
opportunity to improve.

I will definitely work on organizing the website and making it more
user-friendly for beginners in electrical engineering. I understand that
clear organization is important to make it easier for users to find and
learn from the resources I have shared.

Is there anything else you would like to suggest for improvement? I am open
to all feedback and would like to make the website as useful and accessible
as possible.

Thank you again for your time and for your contributions to the electrical
engineering community. I look forward to making the necessary improvements
and making my website a valuable resource for all.

Best regards,
Adhithya
