### ISSUE TITLE
Add Chilipeppr Hardware Fiddle to "Misc. Web Services"

### ISSUE THREAD

**Issue by bmcminn** [kitspace/awesome-electronics#9]
http://chilipeppr.com/

It has workspaces available for driving TinyG, Grbl, Serial, NodeMCU, and Terminal utilities.

**Comment by kasbah** [comment]
Hey, thanks for the link but:

1. The site doesn't load for me on Firefox (Chromium works ok)
2. It seems more like a resource for programming than for electronic engineering?

**Comment by bmcminn** [comment]
The TinyG and Grbl workspaces are for interfacing with CNC machines over webserial, so you can run jobs for enclosures or PCB manufacturing.

The serial, NodeMCU, and Terminal workspaces allow you to interface with program utilities that run on standalone hardware like RaspberryPi's and IoT's devices.

So yes, you can technically program with some of these utilities, but it's a pretty general toolbox for prototyping/manufacturing of a electronics projects as well.

The site runs ok for me in FF 37.0.2, but you may have a content filter/addon that's blocking some part of the page from loading correctly.

**Comment by kasbah** [comment]
Right, yeah it doesn't like uBlock or Privacy Badger. Anyway, I have no way of telling if this is any good unfortunately. It seems a bit confusing (what _is_ it?) so I am going to say no to this unless I can see more feedback that convinces me it works well and is useful.

**Comment by bmcminn** [comment]
A more recent example of Chilipeppr in action from a content creator that specializes in manufacturing https://www.youtube.com/watch?v=gzLYNSQEPDk

**Comment by stevestock** [comment]
@bmcminn I'm not sure this is the right awesome list for this tool.  However, http://chilipeppr.com/ is already in the [awesome-plotters](https://github.com/beardicus/awesome-plotters).  I was not perviously aware of this list, so I made PR sindresorhus/awesome#1768 to make it easier to discover.  Closing for now, but open to discussion if you disagree
