### ISSUE TITLE
Collection of Electrical Engineering resources

### ISSUE THREAD

**Issue by 200901002** [kitspace/awesome-electronics#94]
https://explore.airgapflux.in/

https://airgapflux.in

Hey @kasbah I made website with collection of electrical enginnering resources, see if it's worth your time, thanks.

**Comment by tapyu** [comment]
Hi! I took a look at your resources. Awesome lists rarely contain items for other awesome-like lists, such as your collection of resources, unless the awesome list is a collection of other awesome lists (it is not our case). Therefore, I really advocate not adding your website link as an awesome item. However, if you have you have items you find interesting to share, you can make a PR for them.

One point that we might discuss is how the subsections are organized in the learning section. We have sections that don't seem to cover isolated videos, which is by far the most of your resources AFAIK.
